services:
  - type: web
    name: puppeteer-render-test
    env: node
    plan: free
    buildCommand: npm install && npm run postinstall
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
